### ISSUE TITLE
Miért hasal el a generálás

### ISSUE THREAD

**Issue by wachag** [MIT-EG/Chisel_MiniRISC#1]
https://github.com/MIT-EG/Chisel_MiniRISC/blob/4d776baa93accea6d649d6c979d1123eaa82bc6a/src/main/scala/DataStructure/DataStructure.scala#L64

A hiba oka: az írni akart vezeték (a bal oldalon) a te modulod bemenete. A jobb oldal egy almodul kimenete.
Tehát te modulon belül akartad a saját bemenetedet átírni. Nem data2mem-nek kéne lennie?

**Comment by CsehPeter** [comment]
Köszönöm, javítottam!
