### ISSUE TITLE
Miért nem megy a teszted

### ISSUE THREAD

**Issue by wachag** [MIT-EG/Chisel_MiniRISC#2]
https://github.com/MIT-EG/Chisel_MiniRISC/blob/4d776baa93accea6d649d6c979d1123eaa82bc6a/src/test/scala/DataStructureTest.scala#L34

A hiba oka: te egy memóriának a belsejébe akarnál belenyúlni, és onnan kiolvasni. Ezt sajnos nem tudod megcsinálni. RegisterFile read művelettel (pl. varázsold az adatstruktúra kimenetére a 0. regiszter értékét poke() és step() műveletekkel) tudod ezt elérni.

**Comment by CsehPeter** [comment]
Köszönöm, javítottam!
